version: '3.8'

services:
  postgres:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
      - ./docker/postgres/dumps/:/tmp/
    ports:
      - "5430:5432"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: "Calculator"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: always
volumes:
  database:
    driver: local